// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/documents/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/documents/[id].get').default>>>>
    }
    '/api/documents/:id/audit-trail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/documents/[id]/audit-trail.get').default>>>>
    }
    '/api/documents/:id/transition': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/documents/[id]/transition.post').default>>>>
    }
    '/api/documents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/api/documents/index.post').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/index').default>>>>
    }
  }
}
export {}